version: '3.8'
services:
  db-mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=BE_nestjs
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Ho_Chi_Minh  # Cấu hình múi giờ cục bộ ở đây
    ports:
      - '3308:3306'